networks:
  monitoring-net:
    driver: bridge
    ipam:
      config:
        - subnet: 79.21.0.0/24
          gateway: 79.21.0.1

services:
  apache:
    image: httpd:latest
    container_name: apache_server
    ports:
      - "80:80"  
    volumes:
      - ./apache/apache_status.conf:/usr/local/apache2/conf/extra/httpd-status.conf
    command: >
      sh -c "echo 'Include conf/extra/httpd-status.conf' >> /usr/local/apache2/conf/httpd.conf && httpd-foreground"
    networks:
      monitoring-net:
        ipv4_address: 79.21.0.10 

  apache_exporter:
    image: bitnami/apache-exporter:latest
    container_name: apache_exporter
    command: --scrape_uri=http://79.21.0.10/server-status?auto
    networks:
      monitoring-net:
        ipv4_address: 79.21.0.11
    depends_on:
      - apache

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_server
    ports:
      - "9090:9090" 
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    networks:
      monitoring-net:
        ipv4_address: 79.21.0.20 
    depends_on:
      - apache_exporter 

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_server
    ports:
      - "3000:3000" 
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - grafana-data:/var/lib/grafana
    networks:
      monitoring-net:
        ipv4_address: 79.21.0.30
    depends_on:
      - prometheus
      
volumes:
  grafana-data: